(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(set-fringe-mode '(4 . 4))
(setq frame-resize-pixelwise t)
(push '(font . "PragmataPro VF Mono-11.5") default-frame-alist)
(setq ns-use-proxy-icon nil)
(push '(ns-transparent-titlebar . t) default-frame-alist)
